/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124532-gb4d11dffbf-20260518"
#endif /* AVUTIL_FFVERSION_H */
